# Generated by Django 3.2.8 on 2022-02-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('name', models.CharField(max_length=100, verbose_name='название альбома')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='название группы')),
                ('description', models.TextField(max_length=2000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='автор')),
                ('text', models.TextField(max_length=500, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='жанр')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название песни')),
                ('lyrics', models.TextField(max_length=3000, verbose_name='текст')),
                ('description', models.TextField(blank=True, max_length=4000, null=True, verbose_name='описание')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jc.album')),
                ('genre', models.ManyToManyField(max_length=200, to='jc.Genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('instrument', models.CharField(max_length=30, verbose_name='инструмент')),
                ('info', models.TextField(blank=True, max_length=2000, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jc.band')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='jc.band'),
        ),
    ]
