# Generated by Django 3.1.7 on 2021-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='описание'),
        ),
    ]
