# Generated by Django 3.1.7 on 2021-04-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0002_album_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='автор')),
                ('text', models.TextField(max_length=500, verbose_name='текст')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(max_length=3000, verbose_name='текст'),
        ),
    ]
