# Generated by Django 3.1.7 on 2021-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0003_auto_20210423_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='info',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
