# Generated by Django 3.1.7 on 2021-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0004_person_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
